export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  customerSessionSecret: process.env.LEXY_CUSTOMER_SESSION_SECRET ?? "",
  magicLinkSecret: process.env.LEXY_R1_MAGIC_LINK_SECRET ?? "",
  emailIdentityPepper: process.env.LEXY_R1_EMAIL_IDENTITY_PEPPER ?? "",
  rateLimitPepper: process.env.LEXY_R1_RATE_LIMIT_PEPPER ?? "",
  emailTransport: process.env.LEXY_R1_EMAIL_TRANSPORT ?? "",
  paymentProvider: process.env.LEXY_R1_PAYMENT_PROVIDER ?? "",
  promoVerifier: process.env.LEXY_R1_PROMO_VERIFIER ?? "",
  promoVerifierPepper: process.env.LEXY_R1_PROMO_VERIFIER_PEPPER ?? "",
  promoCampaignId: process.env.LEXY_R1_PROMO_CAMPAIGN_ID ?? "",
  questionnaireIdempotencyPepper:
    process.env.LEXY_R1_QUESTIONNAIRE_IDEMPOTENCY_PEPPER ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
};
